### ISSUE TITLE
No commands/ error at server startup when running on Infinity server with FE installed.

### ISSUE THREAD

**Issue by Cerber91** [MyEssentials/MyTown2#267]
So I'm setting up a FTB Infinity 1.8.2 and it runs fine with just Forge Essentials 1.4 and 1.4.1.(sever can't start unless Fastcraft is disabled). Once I insert ME and MT2, however it can't start. One of the many attempts actually managed to start it up, but everyone could /op themselves and none of the MyTown2 commands were in-game. The mod itself was on the list and within the Forge Essentials permissions categories, so it's definitely loaded, but commands aren't.

**Comment by AfterWind** [comment]
What version of MT2 and MEC are you using?

**Comment by legobear154** [comment]
ForgeEssentials version would be useful as well :)

**Comment by AfterWind** [comment]
This might simply be an issue with ForgeEssentials permission system rather than our mods.
You can try /town, /mytown, townadmin and /mytownadmin. One of those will surely work if you see MyTown2 in your server logs.

**Comment by MacAttack-UK** [comment]
Hi there, OK I'm also running an FTB Infinity 1.8.2 Test Server with additional mods. FE v1.4.1, MT v0.1.1b & ME 1.5r38 (updated from 1.10r after reading another post of yours). As with Cerber91 I see MT etc. in the Forge logs but without errors so to me looks like it's loaded. I've tried all of the commands suggested from both server console and in game but just get "unknown command". I don't really need it so it's not an issue for me but I wanted to take a look to see what it did and look at implementing it onto my main server. If you need logs or anything please let me know. Thanks in advance :)

**Comment by serbaut** [comment]
Maybe this has something to do with it (new to all this and have the same issue)?

    ForgeEssentials/PermissionsList.txt:mytown.adm.cmd # (default: false)
    ForgeEssentials/PermissionsList.txt:mytown.cmd     # (default: false)

**Comment by AfterWind** [comment]
No, that actually says that the commands were registered and it should work properly.

**Comment by serbaut** [comment]
Steps to reproduce with infinity 1.9:

    wget http://ftb.cursecdn.com/FTB2/modpacks/FTBInfinity/1_9_0/FTBInfinityServer.zip
    unzip FTBInfinityServer.zip
    rm mods/fastcraft-1.21.jar
    wget -P mods http://addons-origin.cursecdn.com/files/2248/323/MyTown2-1.7.10-0.1.1b.jar
    wget -P mods http://addons-origin.cursecdn.com/files/2248/672/MyEssentials-Core-1.7.10-1.10r-universal.jar
    wget -P mods http://ci.forgeessentials.com/job/FE/835/artifact/build/libs/forgeessentials-1.7.10-1.4.2.835-server.jar
    echo eula=true > eula.txt
    sh ServerStart.sh

    modlist 11
    [23:15:24] [Server thread/INFO]: --- Showing modlist page 11 of 25 ---
    [23:15:24] [Server thread/INFO]: Thaumic Tinkerer - unspecified
    [23:15:24] [Server thread/INFO]: Forbidden Magic - 1.7.10-0.57
    [23:15:24] [Server thread/INFO]: MyEssentials-Core - 1.7.10-1.10r
    [23:15:24] [Server thread/INFO]: MyTown 2 - 1.7.10-0.1.1b
    [23:15:24] [Server thread/INFO]: Forge Essentials - 1.4.2
    [23:15:24] [Server thread/INFO]: Funky Locomotion - 1.0
    [23:15:24] [Server thread/INFO]: Magic Bees - 1.7.10-2.3.3

    /town
    [23:18:21] [Server thread/INFO]: Unknown command. Try /help for a list of commands
    /mytown
    [23:18:24] [Server thread/INFO]: Unknown command. Try /help for a list of commands
    /townadmin
    [23:18:29] [Server thread/INFO]: Unknown command. Try /help for a list of commands
    /mytownadmin
    [23:18:32] [Server thread/INFO]: Unknown command. Try /help for a list of commands

    /p list groups
    [23:19:00] [Server thread/INFO]: Groups:
    [23:19:00] [Server thread/INFO]:  - _FAKEPLAYERS_
    [23:19:00] [Server thread/INFO]:  - _ALL_
    [23:19:00] [Server thread/INFO]:  - _GUESTS_
    [23:19:00] [Server thread/INFO]:  - _OPS_
    [23:19:00] [Server thread/INFO]:  - command_bubble
    [23:19:00] [Server thread/INFO]:  - _CMDBLOCKS_

**Comment by AfterWind** [comment]
I found out what the issue was. Basically FE changing lots of stuff and we did not implement something properly. Should be fixed now.

**Comment by serbaut** [comment]
Trying to verify this with the latest builds on curse (0.1.2b/1.11r) but it now seems to require MyPermissions which I cant find a build of anywhere?

    [10:45:41] [Server thread/ERROR] [FML]: The following problems were captured during this phase
    [10:45:41] [Server thread/ERROR] [FML]: Caught exception from MyTown2
    java.lang.NoClassDefFoundError: mypermissions/api/IPermissionManager

**Comment by AfterWind** [comment]
Yes that is the cause of the current crash. Still waiting for the Curse staff to approve the project.
